---
# tasks file for kube-apt
- name: Docker apt key 
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Get release
  command: lsb_release -cs
  register: lsb_release

- debug:
    msg: "{{ lsb_release.stdout }}"

- name: Add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable"
    state: present
    filename: 'docker'

- name: Kubernetes apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes repo
  apt_repository:
    repo: "deb [arch=amd64] http://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: 'kubernetes'

- name: Set apt docker pinning
  copy:
    dest: /etc/apt/preferences.d/docker
    content: |
      Package: *
      Pin: release o=Docker,a=focal,l=Docker CE,c=stable,b=amd64
      Pin-Priority: 900

- name: Set apt kube pinning
  copy:
    dest: /etc/apt/preferences.d/kubernetes
    content: |
      Package: *
      Pin: release o=kubernetes-xenial,a=kubernetes-xenial,n=kubernetes-xenial,l=kubernetes-xenial,c=main,b=amd64
      Pin-Priority: 900
...            
